gun1=int(input("1.gün okunan kitap sayısını yazınız:"))
gun2=int(input("2.gün okunan kitap sayısını yazınız:"))
gun3=int(input("3.gün okunan kitap sayısını yazınız:"))
gun4=int(input("4.gün okunan kitap sayısını yazınız:"))
gun5=int(input("5.gün okunan kitap sayısını yazınız:"))
gun6=int(input("6.gün okunan kitap sayısını yazınız:"))
gun7=int(input("7.gün okunan kitap sayısını yazınız:"))
toplam=(gun1+gun2+gun3+gun4+gun5+gun6+gun7)
print("7. günün okudugu kitap sayısınız toplamı:",toplam)